### ISSUE TITLE
首先感谢小多，我在将golang代码转换到C++代码时发现了一个问题，跟你分享一下

### ISSUE THREAD

**Issue by ljc545w** [duo/gommtls#1]
有时候session序列化后长度是177字节，这时候ticket的数量是1，所以修改下面两处代码：
![企业微信截图_16950337033185](https://github.com/duo/gommtls/assets/67629154/e4f3aaf8-5224-4544-bc37-2a2ff60474a6)
![企业微信截图_1695033745407](https://github.com/duo/gommtls/assets/67629154/12dd90c1-f844-494f-8054-2a0a424a07c9)

**Comment by ljc545w** [comment]
C++代码：[mmtls](https://github.com/ljc545w/mmtls)

**Comment by duo** [comment]
Fixed at https://github.com/duo/gommtls/commit/d82b1a1ef921f3e6a1ef124ccf6a935036e66646, thanks!
